POST http://localhost:8081/api/v1/events HTTP/1.1
Content-Type: application/json

{
  "event": "sined_up",
  "user_id": "user123",
  "client_ts": "2024-06-01T12:00:00Z",
  "metadata": {
     "button": "signup"
  }
}

###
GET http://localhost:8081/api/v1/events?user_id=user124&limit=20 HTTP/1.1
Accept: application/json

###

DELETE http://localhost:8081/api/v1/events HTTP/1.1

###

POST http://localhost:8081/api/v1/events HTTP/1.1
Content-Type: application/json
X-Request-ID: req_custom_xyz

{
  "event": "user_login",
  "user_id": "user789",
  "client_ts": "2024-06-01T13:00:00Z",
  "metadata": {
    "method": "oauth"
  }
}
