# Generated by Django 6.0.1 on 2026-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("received_at", models.DateTimeField()),
                ("client_ts", models.DateTimeField()),
                ("event", models.CharField(max_length=64)),
                ("user_id", models.CharField(max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                ("request_id", models.CharField(max_length=64)),
            ],
        ),
    ]
